services:
  orderer.example.com:
    container_name: orderer.example.com
    image: ghcr.io/aho-ui/fabric-orderer-seed:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - seed_network

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: ghcr.io/aho-ui/fabric-peer-org1-seed:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=seed_network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    depends_on:
      - orderer.example.com
    networks:
      - seed_network

  fabric-client:
    container_name: fabric-client
    image: ghcr.io/aho-ui/fabric-client-seed:latest
    ports:
      - "3000:3000"
    depends_on:
      - peer0.org1.example.com
      - orderer.example.com
    networks:
      - seed_network

  postgres:
    image: pgvector/pgvector:pg18
    container_name: seed_postgres
    environment:
      POSTGRES_DB: seed_db
      POSTGRES_USER: seed_user
      POSTGRES_PASSWORD: seed_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - seed_network
    logging:
      driver: "none"

  backend:
    image: ghcr.io/aho-ui/seed_backend:ecdsa
    container_name: seed_backend
    depends_on:
      - postgres
      - ml-server
    environment:
      DATABASE_URL: postgresql://seed_user:seed_password@postgres:5432/seed_db
      POSTGRES_DB: seed_db
      POSTGRES_USER: seed_user
      POSTGRES_PASSWORD: seed_password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      url: http://ml-server:8001
      FABRIC_URL: http://fabric-client:3000
      SAWTOOTH_URL: http://sawtooth-client:9000
    ports:
      - "8000:8000"
    networks:
      - seed_network

  frontend:
    image: ghcr.io/aho-ui/seed_frontend:latest
    container_name: seed_frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"
    networks:
      - seed_network

  ml-server:
    image: ghcr.io/aho-ui/seed_ml-server:latest
    container_name: seed_ml_server
    ports:
      - "8001:8001"
    networks:
      - seed_network

  sawtooth-validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - "4004:4004"
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://sawtooth-validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""
    networks:
      - seed_network

  sawtooth-devmode:
    image: hyperledger/sawtooth-devmode-engine-rust:latest
    container_name: sawtooth-devmode
    depends_on:
      - sawtooth-validator
    entrypoint: devmode-engine-rust -C tcp://sawtooth-validator:5050
    networks:
      - seed_network

  sawtooth-rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: sawtooth-rest-api
    ports:
      - "8008:8008"
    depends_on:
      - sawtooth-validator
    entrypoint: sawtooth-rest-api -C tcp://sawtooth-validator:4004 --bind sawtooth-rest-api:8008
    networks:
      - seed_network
    logging:
      driver: "none"

  sawtooth-settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp
    depends_on:
      - sawtooth-validator
    entrypoint: settings-tp -vv -C tcp://sawtooth-validator:4004
    networks:
      - seed_network
    logging:
      driver: "none"

  seed-tp:
    image: ghcr.io/aho-ui/seed-tp:ecdsa
    container_name: seed-tp
    depends_on:
      - sawtooth-validator
    command: python3 seed.py
    networks:
      - seed_network

  sawtooth-client:
    image: ghcr.io/aho-ui/sawtooth-client:ecdsa
    container_name: sawtooth-client
    depends_on:
      - sawtooth-rest-api
    ports:
      - "9000:9000"
    environment:
      VALIDATOR_URL: http://sawtooth-rest-api:8008
    networks:
      - seed_network

volumes:
  postgres_data:

networks:
  seed_network:
    external: true